system:
  addr: 8800

mysql:
  path: 172.20.0.2
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: palserver
  username: root
  password: "123456"
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false

redis:
  db: 0
  addr: 172.20.0.3:6379
  password: ""

zap:
  level: info
  prefix: "[github.com/yaoyaochil/pal-pannel-server]"
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

jwt:
  signing-key: 53fff5b5-4d84-464a-bbe1-d955cd2cd714
  expires-time: 7d
  buffer-time: 1d
  issuer: palserveradmin

palu:
  init: false
  server-path: "/home/steam/Steam/steamapps/common/PalServer/"

command:
  logout-path: "log/command.log"